### PR TITLE
README.md updated.

### PR DESCRIPTION
**Pull request by danirueda**

### CODE REVIEW

**Comment by fjlopez** [comment]
Think, there is something missing in your work. Which is the role of Eureka?

**Comment by danirueda** [comment]
Thre Eureka role is being an microservices orchestrator. Eureka give us the control of all the microservices that are registered on it. It's similar to a RMI register.

**Comment by fjlopez** [comment]
It does something additional that you have not explained yet that is really really key. Have you tested the web application? Please, do it and try to understand and explain how this web application uses Eureka.

**Comment by danirueda** [comment]
@fjlopez My test branch is updated. Now I have understood the behaviour of Eureka. I didn't test the web service before.

**Pull request merged**
